/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sips.view;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author NeftaliJunior
 */
public class telaAssistente extends javax.swing.JFrame {

    /**
     * Creates new form telaAssistente
     */
    public telaAssistente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mAltSenha = new javax.swing.JMenuItem();
        mSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mCriarProgSoc = new javax.swing.JMenuItem();
        mProgSoc = new javax.swing.JMenuItem();
        mCriarSelec = new javax.swing.JMenuItem();
        mSelec = new javax.swing.JMenuItem();
        mAlunos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mResultSelec = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Assistente");

        jDesktopPane1.setBackground(new java.awt.Color(66, 82, 97));
        jDesktopPane1.setToolTipText("");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sips/img/logo128.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bem vindo Assistente!");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sips/img/assistente.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel2)
                .addContainerGap(281, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(110, 110, 110))
        );

        jMenu1.setText("Meu Perfil");
        jMenu1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        mAltSenha.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        mAltSenha.setText("Alterar Senha");
        mAltSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAltSenhaActionPerformed(evt);
            }
        });
        jMenu1.add(mAltSenha);

        mSair.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        mSair.setText("Sair");
        mSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSairActionPerformed(evt);
            }
        });
        jMenu1.add(mSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Programas Sociais");
        jMenu2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        mCriarProgSoc.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        mCriarProgSoc.setText("Criar Programa Social");
        mCriarProgSoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCriarProgSocActionPerformed(evt);
            }
        });
        jMenu2.add(mCriarProgSoc);

        mProgSoc.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        mProgSoc.setText("Programas Sociais");
        mProgSoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mProgSocActionPerformed(evt);
            }
        });
        jMenu2.add(mProgSoc);

        mCriarSelec.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        mCriarSelec.setText("Criar Seleção");
        mCriarSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCriarSelecActionPerformed(evt);
            }
        });
        jMenu2.add(mCriarSelec);

        mSelec.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        mSelec.setText("Seleções");
        mSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSelecActionPerformed(evt);
            }
        });
        jMenu2.add(mSelec);

        mAlunos.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        mAlunos.setText("Alunos");
        mAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAlunosActionPerformed(evt);
            }
        });
        jMenu2.add(mAlunos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Informativos");
        jMenu3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        mResultSelec.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        mResultSelec.setText("Result. das Seleções");
        mResultSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mResultSelecActionPerformed(evt);
            }
        });
        jMenu3.add(mResultSelec);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mAltSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAltSenhaActionPerformed
        
        telaInAlterarSenha telaAltSenha = new telaInAlterarSenha();
        jDesktopPane1.add(telaAltSenha);
        telaAltSenha.setVisible(true);
        
    }//GEN-LAST:event_mAltSenhaActionPerformed

    private void mCriarProgSocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCriarProgSocActionPerformed
        
        telaInCriarProgramaSocial telaCProgSoc = new telaInCriarProgramaSocial();
        jDesktopPane1.add(telaCProgSoc);
        telaCProgSoc.setVisible(true);
        
    }//GEN-LAST:event_mCriarProgSocActionPerformed

    private void mProgSocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mProgSocActionPerformed
        
        telaInProgramasSociais telaCProgSoc = new telaInProgramasSociais();
        jDesktopPane1.add(telaCProgSoc);
        telaCProgSoc.setVisible(true);
        
    }//GEN-LAST:event_mProgSocActionPerformed

    private void mCriarSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCriarSelecActionPerformed
        
        telaInCriarSelec telaCSelec = new telaInCriarSelec();
        jDesktopPane1.add(telaCSelec);
        telaCSelec.setVisible(true);
        
    }//GEN-LAST:event_mCriarSelecActionPerformed

    private void mSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSelecActionPerformed
       
        telaInSelecoes telaSelecoes = new telaInSelecoes();
        jDesktopPane1.add(telaSelecoes);
        telaSelecoes.setVisible(true);
        
    }//GEN-LAST:event_mSelecActionPerformed

    private void mAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAlunosActionPerformed
        
        telaInListaAlunos telaListaAlunos = new telaInListaAlunos();
        jDesktopPane1.add(telaListaAlunos);
        telaListaAlunos.setVisible(true);
        
    }//GEN-LAST:event_mAlunosActionPerformed

    private void mResultSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mResultSelecActionPerformed
       
       telaInResultSelec telaResultSelec = new telaInResultSelec();
       jDesktopPane1.add(telaResultSelec);
       telaResultSelec.setVisible(true);
       
    }//GEN-LAST:event_mResultSelecActionPerformed

    private void mSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSairActionPerformed
        //implementar para fechar sessão
        new telaLogin().setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_mSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaAssistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaAssistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaAssistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaAssistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaAssistente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mAltSenha;
    private javax.swing.JMenuItem mAlunos;
    private javax.swing.JMenuItem mCriarProgSoc;
    private javax.swing.JMenuItem mCriarSelec;
    private javax.swing.JMenuItem mProgSoc;
    private javax.swing.JMenuItem mResultSelec;
    private javax.swing.JMenuItem mSair;
    private javax.swing.JMenuItem mSelec;
    // End of variables declaration//GEN-END:variables
}
