/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sips.view;

/**
 *
 * @author NeftaliJunior
 */
public class telaAluno extends javax.swing.JFrame {

    /**
     * Creates new form telaAluno
     */
    public telaAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mAltDados = new javax.swing.JMenuItem();
        mAltSenha = new javax.swing.JMenuItem();
        mSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mProgSoc = new javax.swing.JMenuItem();
        mSelec = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aluno");
        setBackground(new java.awt.Color(255, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(66, 82, 97));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sips/img/logo128.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sips/img/aluno.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bem vindo Aluno!");

        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel2)
                .addContainerGap(281, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(110, 110, 110))
        );

        jMenu1.setText("Meu Perfil");
        jMenu1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        mAltDados.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        mAltDados.setText("Alterar Dados");
        mAltDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAltDadosActionPerformed(evt);
            }
        });
        jMenu1.add(mAltDados);

        mAltSenha.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        mAltSenha.setText("Alterar Senha");
        mAltSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAltSenhaActionPerformed(evt);
            }
        });
        jMenu1.add(mAltSenha);

        mSair.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        mSair.setText("Sair");
        mSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSairActionPerformed(evt);
            }
        });
        jMenu1.add(mSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Programas Sociais");
        jMenu2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        mProgSoc.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        mProgSoc.setText("Programas Sociais");
        mProgSoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mProgSocActionPerformed(evt);
            }
        });
        jMenu2.add(mProgSoc);

        mSelec.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        mSelec.setText("Seleções");
        mSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSelecActionPerformed(evt);
            }
        });
        jMenu2.add(mSelec);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mAltDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAltDadosActionPerformed
      
        //abre tela para alterar senha
        telaInAlterarDados telaAltDados = new telaInAlterarDados();
        jDesktopPane1.add(telaAltDados);
        telaAltDados.setVisible(true);
        
    }//GEN-LAST:event_mAltDadosActionPerformed

    private void mAltSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAltSenhaActionPerformed
        
        //abre tela para alterar senha
        telaInAlterarSenha telaAltSenha = new telaInAlterarSenha();
        jDesktopPane1.add(telaAltSenha);
        telaAltSenha.setVisible(true);
        
    }//GEN-LAST:event_mAltSenhaActionPerformed

    private void mProgSocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mProgSocActionPerformed
        
        //abre tela dos programas sociais
        telaInProgramasSociais telaProgSociais = new telaInProgramasSociais();
        jDesktopPane1.add(telaProgSociais);
        telaProgSociais.setVisible(true);
    }//GEN-LAST:event_mProgSocActionPerformed

    private void mSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSelecActionPerformed
        
        //abre tela das selecoes
        telaInSelecoes telaSelecoes = new telaInSelecoes();
        jDesktopPane1.add(telaSelecoes);
        telaSelecoes.setVisible(true);
        
    }//GEN-LAST:event_mSelecActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void mSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSairActionPerformed
        //implementar para fechar sessão
       new telaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mAltDados;
    private javax.swing.JMenuItem mAltSenha;
    private javax.swing.JMenuItem mProgSoc;
    private javax.swing.JMenuItem mSair;
    private javax.swing.JMenuItem mSelec;
    // End of variables declaration//GEN-END:variables
}
