/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sips.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import sips.bo.ProgramaBO;
import sips.model.Programa;

/**
 *
 * @author NeftaliJunior
 */
public class telaInProgramasSociais extends javax.swing.JInternalFrame {

    /**
     * Creates new form telaInProgramasSociais
     */
    public telaInProgramasSociais() {
        initComponents();
        carregarProgramas();
    }
    private void carregarProgramas(){
        ProgramaBO progBO =  new ProgramaBO();
        ArrayList<Programa> programas =  progBO.listarProgramas();
        for (int i = 0; i < programas.size(); i++) {
            DefaultTableModel modelo = (DefaultTableModel)tblPrograma.getModel();
            modelo.addRow(new Object[]{programas.get(i).getNome(),programas.get(i).getValor(),programas.get(i).getDescricao()});
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPrograma = new javax.swing.JTable();

        setBackground(new java.awt.Color(66, 82, 97));
        setClosable(true);
        setResizable(true);
        setTitle("Programas Sociais");

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Programas Sociais");

        tblPrograma.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        tblPrograma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Valor", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPrograma.setGridColor(new java.awt.Color(66, 82, 97));
        jScrollPane5.setViewportView(tblPrograma);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel1)
                .addContainerGap(361, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblPrograma;
    // End of variables declaration//GEN-END:variables
}
